import "@/app/globals.css";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import { Geist } from "next/font/google";
import { Sidebar } from "@/components/Sidebar";

const geist = Geist({
  subsets: ["latin"],
});

interface Props {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={`dark ${geist.className}`}>
      <body className="w-screen h-screen bg-background text-foreground grid grid-cols-[1.5fr_10fr] grid-rows-1 divide-x divide-border">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
