import "@/app/globals.css";

import type { Metadata } from "next";
import type { ReactNode } from "react";

interface Props {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className="dark">
      <body className="grid grid-cols-[1fr_1fr_4fr] grid-rows-[50px_50px_1fr_50px] w-screen h-screen bg-background text-foreground">
        {children}
      </body>
    </html>
  );
}
